### ISSUE TITLE
Readme Cmake Command Bug

### ISSUE THREAD

**Issue by Exairnous** [wheybags/freeablo#175]
In the readme it says to cd to build and then run cmake ../freeablo, this causes an error.  The command should be cmake ../

**Comment by mewmew** [comment]
I thought so too at first. But after closer examination of the build instructions in the readme, it turns out that I had misinterpreted the directory structure. Basically the `build` directory exists in the same parent directory which contains the `freeablo` directory, that is the `build` directory is not a sub-directory of the `freeablo` directory (which is common for build instructions of other projects).

```bash
$ ls
build/
freeablo/
...
```

Based on this directory structure, running `cmake ../freeablo` from within the `build` directory makes sense.

**Comment by Exairnous** [comment]
You're right, my mistake.  Closing.

**Comment by mewmew** [comment]
If this comes up again, maybe the readme should be changed to use a `build`-dir which is a subdirectory of the `freeablo` directory, as this is a common directory structure used by other projects.
