### ISSUE TITLE
The graphic glitch in the right corner of the game (Mac/Ubuntu)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#227]
Hi

I noticed this weird bug in the game when I tried to run Freeablo with graphic resolution higher than 1280 x 720:

https://www.youtube.com/watch?v=FCCg-pd-NII

Do you have a similar problem?

**Comment by konopka90** [comment]
Yes but it is known issue because there is nothing to render - just end of map. When you go to the top left or top right corner you will see the same problem. In Diablo 1 as I remember max resolution was 640x480 so there was no such problem. Anyway, it is interesting how to fill area outside of original map.

**Comment by gbudny** [comment]
I checked it, and I noticed a similar bug in the top left corner:

I think there shouldn't be this blinking effect when I move menus in these areas of the game. In the second movie this bug looks worse:

https://www.youtube.com/watch?v=irK36GlNhA8&feature=youtu.be

**Comment by Ragora** [comment]
It will do that with any sort of pixels that enter and leave those regions of the map on screen as the buffer is never drawn to on subsequent frames which means pixels that were once there will simply hang around, creating that glitchy effect. There's nothing to draw for that section of the screen and 2D rasters typically will just keep drawing into the buffer wherever they're told to unless explicitly told to "clear" (which just fills the entire buffer with some color) which should at least be a easy work around for the short term. 

Clear buffer with black, then run the normal draw routines so that then the clear nukes any pixels that are hanging around. A proper fix, for outdoor environments at least, would involve filling in the empty screen space with more tiles so that there never is empty screen space to ever see.

Using something like SDL_FillRect to fill the screen at the start of every frame with black pixels should at least remedy the problem.

**Comment by konopka90** [comment]
Do you have any idea what should be drawn there? Maybe custom tiled texture? Drawing only black color wouldn't be so nice.

**Comment by Ragora** [comment]
You either need to have the map extended and stop the camera from moving before it reaches the true end of the map or simply stop the camera before it reaches the end of the map. 

The former is probably the most likely the solution but it will need done for every level suffering the problem and drawing black isn't acceptable (Eg. drawing black is acceptable for a dungeon). Reason why it needs done manually is we can't just fill in something like grass because that will look awkward in specific sections of the map there because it doesn't match.

**Comment by mewmew** [comment]
> Do you have any idea what should be drawn there? Maybe custom tiled texture? Drawing only black color wouldn't be so nice.

If you turn of collision in Diablo 1 (edit SOL files, or the asm) you can walk to the edge of the map. Anything outside of the map is rendered black. This is also true for any transparent regions on the map, such as the transparent triangle in Griswold's blacksmith shop, which is rendered black.

**Comment by Ragora** [comment]
Then rendering black would be the most accurate solution but you also weren't intended to ever see the non-rendered areas either.

**Comment by mewmew** [comment]
> Then rendering black would be the most accurate solution but you also weren't intended to ever see the non-rendered areas either.

That's true

**Comment by wheybags** [comment]
fixed at some point, we now draw infintie tiles out from the edge
