### ISSUE TITLE
When selling items, we should make sure we have room to receive the gold

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#397]

**Comment by akuskis** [comment]
Is it ok, if gold that can't be put into inventory will be thrown on the ground?
![image](https://user-images.githubusercontent.com/3109998/59339189-60858d80-8d0c-11e9-8c7a-71c8641ef599.png)

**Comment by AJenbo** [comment]
In the original it would check if you have room for the gold and show you the "No room" (same as if you tried to buy something that you do not have room for) message if you do not have room for the gold.

Also what would happen if all tiles around you are occupied by items already?

**Comment by akuskis** [comment]
Thank you, now It's clear.
I have to install original one on wine, to do not spam here with simple questions.

**Comment by AJenbo** [comment]
No worries, I'm happy to look up stuff like this to help out.

**Comment by wheybags** [comment]
closed by #443

**Comment by AJenbo** [comment]
> Thank you, now It's clear.
> I have to install original one on wine, to do not spam here with simple questions.

Since running, Diablo from Wine can be a bit of a pain I would suggest using DevilutionX instead. It's 99% accurate to the original 1.09 running on Windows 98 on a 60hz monitor (some timings are wrong when running on WindowsNT or a high hz monitor), and most of the differences are down to the error messages. It also allows you to run in windows mode which can be very handy for testing.
